
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 12 20:29:09 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 15;
  public static final int MENORQI = 6;
  public static final int NOTR = 10;
  public static final int DECIMAL = 13;
  public static final int ANDR = 8;
  public static final int POT = 18;
  public static final int MENORQ = 5;
  public static final int MAYORQI = 7;
  public static final int ID = 11;
  public static final int MAYORQ = 4;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int DIV = 17;
  public static final int PAR_IZQ = 19;
  public static final int error = 1;
  public static final int PAR_DER = 20;
  public static final int ENTERO = 12;
  public static final int DIFE = 3;
  public static final int ORR = 9;
  public static final int MAS = 14;
  public static final int IGUAL2 = 2;
}

